package com.yulin.viewpager;

public class Data {

    public static String[] imageUrls = {
            "https://kano.guahao-test.com/qja28048791",
            "https://kano.guahao-test.com/VN428048790",
            "https://kano.guahao-test.com/7tC28048789",
            "https://kano.guahao-test.com/p0m28048788",
            "https://kano.guahao-test.com/XBr28048787",
            "https://kano.guahao-test.com/T1W28048786",
            "https://kano.guahao-test.com/ayA28048785",
            "https://kano.guahao-test.com/dhT28048784",
            "https://kano.guahao-test.com/0Bh28048783",
            "https://kano.guahao-test.com/k9p28048792",
            "https://kano.guahao-test.com/tqZ28048793",
            "https://kano.guahao-test.com/OaS28048794",
            "https://kano.guahao-test.com/gn928048795",
            "https://kano.guahao-test.com/cJG28048796",
            "https://kano.guahao-test.com/9pN28048797",
            "https://kano.guahao-test.com/Jx928048798",
            "https://kano.guahao-test.com/upx28048799",
            "https://kano.guahao-test.com/4J628048800",
            "https://kano.guahao-test.com/bsn28048802",
            "https://kano.guahao-test.com/8UO28048803",
            "https://kano.guahao-test.com/SW328048804",
            "https://kano.guahao-test.com/SQY28048805",
            "https://kano.guahao-test.com/k7k28048806",
            "https://kano.guahao-test.com/bwP28048807",
            "https://kano.guahao-test.com/jYI28048808"
    };

    public static String[] aliyunImageUrls = {
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image01.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image02.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image03.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image04.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image05.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image06.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image07.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image08.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image09.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image10.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image11.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image12.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image13.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image14.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image15.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image16.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image17.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image18.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image19.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image20.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image21.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/image22.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu01.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu02.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu03.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu04.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu05.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu06.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu07.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu08.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu09.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu10.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu11.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu12.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu13.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu14.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu15.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu16.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu17.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu18.jpg",
            "https://yulinwork.oss-cn-hangzhou.aliyuncs.com/image/yunhaifu19.jpg"
    };

}
